### PR TITLE
Follow request acceptance

### PR DESCRIPTION
**Pull request by cthulahoops**
Basic working interface for issue #82 now.

Still need to generate Reject activity. Probably need to store full follow request in the database to populate the Accept/Reject activity.

Really need to get a multi-node test setup to check this really works with multiple nodes.

### CODE REVIEW

**Comment by cthulahoops** [comment]
I think that works properly now with rejections crossing between nodes. I'm thinking the next focus needs to be getting some testing with multiple nodes set up.

**Comment by mouse-reeve** [comment]
I've been using my localhost vs fedireads-test.glitch.me for cross-instance testing, fwiw

**Comment by mouse-reeve** [comment]
oh though I guess I'm the only one who can put code there so that's not helpful to anyone besides me, oops

**Comment by mouse-reeve** [comment]
thank you for fixing my fake enums!

**Comment by cthulahoops** [comment]
> oh though I guess I'm the only one who can put code there so that's not helpful to anyone besides me, oops

There's at least some testing I can run with control over one half of things, and I guess I can set up my own node some too. It should be possible to get two nodes both running on localhost, I just haven't really tried yet.

I'd really like to get some sort of automated testing in place. It's a lot of effort to test some of these interactions.

**Pull request merged**
